logger:
  pattern.console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %msg%n"

spring:
  #profiles: default
  datasource:
    #url: jdbc:h2:file:/Users/amandeepsingh/CodeConcepts/Arch/design/git/design-solutions/tmf/db/tmf
    url: jdbc:h2:tcp://localhost/~/CodeConcepts/Arch/design/git/design-solutions/tmf/db/tmf
    driverClassName: org.h2.Driver
  jpa.hibernate.ddl-auto: create
  jpa.properties.javax.persistence.schema-generation.script.action: create
  jpa.properties.javax.persistence.schema-generation.script.create-target: create.sql

tmf:
  taskTableCreateQuery: create table task (id number primary key)

---